sudo: required
services:
  - docker

before_install:
  - docker build -t meryemwehbe/dockercourse -f Dockerfile.dev .

script:
  - docker run -e CI=true meryemwehbe/dockercourse npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerCourse"
  env: "Dockercourse-env"
  bucket_name: "elasticbeanstalk-us-east-2-589696110364"
  bucket_pack: "DockerCourse"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: :$AWS_SECRET_KEY

